# Generated by Django 4.2.11 on 2024-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_userprofile_user_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
