# Generated by Django 4.2.11 on 2024-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
