# Generated by Django 4.2.11 on 2024-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_userseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userseen',
            name='users_seen',
        ),
        migrations.AddField(
            model_name='userseen',
            name='user_seen_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
