# Generated by Django 4.2.11 on 2024-04-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_userseen_users_seen_userseen_user_seen_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userseen',
            options={'ordering': ['user_seen_id']},
        ),
    ]
