# Generated by Django 4.2.11 on 2024-04-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_dbpointer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbpointer',
            old_name='prefference',
            new_name='preference',
        ),
    ]
